# This workflow will do a clean install of the dependencies and run tests across different versions
#
# Replace <track> with the track name
# Replace <image-name> with an image to run the jobs on
# Replace <action to setup tooling> with a github action to setup tooling on the image
# Replace <install dependencies> with a cli command to install the dependencies
#
# Find Github Actions to setup tooling here:
# - https://github.com/actions/?q=setup&type=&language=
# - https://github.com/actions/starter-workflows/tree/main/ci
# - https://github.com/marketplace?type=actions&query=setup
#
# Requires scripts:
# - bin/test

name: arm32-assembly / Test

on:
  push:
    branches: [master, main]
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]

    steps:
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: Install project dependencies
        run: |
          sudo apt update -q
          sudo apt install -y qemu-user gcc-arm-linux-gnueabihf binutils-arm-linux-gnueabihf

      - name: Run exercism/arm32-assembly test (runs tests) for all exercises
        env:
          CC: ${{ matrix.compiler }}
          CC_FOR_BUILD: ${{ matrix.compiler }}
        run: bin/verify-exercises
